# Módulo 2: Limpeza de Dados

Esse módulo trata do pre-processamento de dados. As atividades descritas nesse módulo referem-se a limpeza e ajustamento de dados, parte essencial para a etapa de modelagem estatística.

### Objetivos de aprendizado para esse módulo

 * Lidar com valores faltantes
 * Aplicar técnicas de formatação de dados
 * Padronizar dados
 * Classificar dados em intervalo
 * Utilizar variáveis categóricas
 
***

### Lidando com valores faltantes

Não raro datasets possuem ruído, alguma lacuna que pode ser derivada tanto de um problema no processo de coleta de dados como a inexistencia da informação para determinada observação. 

Nos datasets esses casos podem ser representados como `?`, `NA`, `0`, ou mesmo uma _celula vazia_.  

O que se segue nesses casos é uma decisão do analista que pode ser simplesmente ignorar o problema até o extremo de eliminar a observação do dadtaset

Da decisão mais para menos drástica, temos 

 * o método `dropna` que elimina a observação do dataset
 

###

In [3]:
import pandas as pd # importa pandas, que pode ser lido como 'pd'

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data" # string que recebe a localização do dataset

df = pd.read_csv(url, header = None) # método que lê o dataset

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625